---

- name: Ensure jitsi directories do not exist
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "/mnt/jitsi"
    - "/root/.jitsi-meet-cfg"

- name: Ensure jitsi config directories exists
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "/mnt/jitsi"
    - "/root/.jitsi-meet-cfg/web/letsencrypt"
    - "/root/.jitsi-meet-cfg/transcripts"
    - "/root/.jitsi-meet-cfg/prosody"
    - "/root/.jitsi-meet-cfg/jicofo"
    - "/root/.jitsi-meet-cfg/jvb"

- name: Clone the jitsi docker image
  git:
    repo: https://github.com/jitsi/docker-jitsi-meet
    dest: /mnt/jitsi
    update: yes
    recursive: yes

- name: Build the docker immages
  shell: |
    tmux new-session -s "make" "cd /mnt/jitsi && FORCE_REBUILD=1 make | tee /var/log/jitsibuild.log; true"

- name: Copy .env file
  template:
    src: env.j2
    dest: /mnt/jitsi/.env

- name: Fix passwords in .env file
  shell: |
    cd /mnt/jitsi
    ./gen-passwords.sh
  when: jitsi_generate_random_password|bool == true

- name: fix python docker
  shell: |
    pip uninstall docker-py --yes; pip uninstall docker --yes; pip install docker

- name: Copy systemd unit
  template:
    src: jitsi.service.j2
    dest: /etc/systemd/system/jitsi.service

- name: Start the jitsi service
  systemd:
    name: jitsi
    state: restarted
    enabled: yes
    daemon_reload: yes

